version: "3"

services:
  results:
    build: .
    depends_on:
      - 'database'
    ports:
      - '5432:5432'

  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret-33-sauce